repos:
  - repo: https://github.com/psf/black
    rev: 21.12a0
    hooks:
      - id: black
        language_version: python3.10
        files: ^uploads/ ^env/
  - repo: https://github.com/PyCQA/flake8
    rev: v3.9.2
    hooks:
      - id: flake8
        args:
              - --max-line-length=79
        files: ^uploads/ ^env/
