# Generated by Django 4.1.7 on 2023-03-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="file",
            table="files",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
